#pragma once

#define WIFI_SSID "YOUR_WIFI_SSID"
#define WIFI_PASS "YOUR_WIFI_PASS"

#define FIREBASE_HOST "YOUR_FIREBASE_HOST"
#define API_KEY "YOUR_FIREBASE_API_KEY"
#define DB_EMAIL "YOUR_FIREBASE_EMAIL"
#define DB_PASS "YOUR_FIREBASE_PASS"

#define BTN_HOLD_PIN 13
#define BTN_TARE_PIN 14
#define BTN_MODE_PIN 15

#define DEBUG_BUTTONS 1

